import {
  BuildRequestWithRelations,
  Category,
  Profile,
  Prompt,
  PromptStep,
  SuggestionResponse,
  SuggestionWithRelations,
} from './types'
import { SNAKE_PROJECT_ID } from './featured-projects'
import {
  FLASHCARD_CRAM_SHOWCASE_PROJECT,
  FOLLOW_UP_CRM_SHOWCASE_PROJECT,
  HP_10BII_SHOWCASE_PROJECT,
  LANE_DEFENSE_SHOWCASE_PROJECT,
  MEETING_COST_SHOWCASE_PROJECT,
  NEON_BLOCK_PATROL_SHOWCASE_PROJECT,
  POCKET_RALLY_SHOWCASE_PROJECT,
  POMODORO_TIMER_SHOWCASE_PROJECT,
  PUZZLE_BOX_ESCAPE_SHOWCASE_PROJECT,
  REACTION_TRAINER_SHOWCASE_PROJECT,
  SWISH_CITY_SHOWCASE_PROJECT,
  TIC_TAC_TOE_SHOWCASE_PROJECT,
  TRIP_PACKING_SHOWCASE_PROJECT,
  WEEKEND_CHECKLIST_SHOWCASE_PROJECT,
  WORD_LADDER_SPRINT_SHOWCASE_PROJECT,
  PENDING_SOURCE_RUN_SHOWCASE_PROJECTS,
} from './prepared-showcase-projects'
import type { PreparedShowcaseProject } from './prepared-showcase-projects'

const PENDING_SOURCE_RUN_PROFILE_ID_START = 227

function pendingSourceRunProfileId(index: number) {
  return `22222222-2222-2222-2222-${String(PENDING_SOURCE_RUN_PROFILE_ID_START + index).padStart(12, '2')}`
}

export const mockProfiles: Profile[] = [
  {
    id: '22222222-2222-2222-2222-222222222211',
    username: 'pathforge_projects',
    display_name: 'PathForge Projects',
    avatar_url: null,
    bio: 'Approved PathForge seed projects with real prompts, captured responses, and playable artifacts.',
    role: 'user',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-05-24T16:15:00Z',
  },
  {
    id: '22222222-2222-2222-2222-222222222212',
    username: HP_10BII_SHOWCASE_PROJECT.authorUsername,
    display_name: HP_10BII_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Finance and browser-tool builds submitted through PathForge source runs.',
    role: 'user',
    created_at: '2026-06-01T01:07:00Z',
    updated_at: HP_10BII_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222213',
    username: TIC_TAC_TOE_SHOWCASE_PROJECT.authorUsername,
    display_name: TIC_TAC_TOE_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Basic browser-game builds submitted through PathForge source runs.',
    role: 'user',
    created_at: '2026-05-30T21:30:00Z',
    updated_at: TIC_TAC_TOE_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222214',
    username: POMODORO_TIMER_SHOWCASE_PROJECT.authorUsername,
    display_name: POMODORO_TIMER_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Productivity and focus-tool builds grown one prompt at a time through PathForge source runs.',
    role: 'user',
    created_at: '2026-06-02T17:55:00Z',
    updated_at: POMODORO_TIMER_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222215',
    username: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.authorUsername,
    display_name: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Productivity builds and planning tools submitted through PathForge source runs.',
    role: 'user',
    created_at: '2026-06-03T23:46:00Z',
    updated_at: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222216',
    username: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.authorUsername,
    display_name: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Playable browser-game prototypes submitted through PathForge source runs.',
    role: 'user',
    created_at: '2026-06-04T01:05:00Z',
    updated_at: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222217',
    username: SWISH_CITY_SHOWCASE_PROJECT.authorUsername,
    display_name: SWISH_CITY_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Arcade-style browser games and timing experiments submitted through PathForge source runs.',
    role: 'user',
    created_at: '2026-06-04T01:06:00Z',
    updated_at: SWISH_CITY_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222218',
    username: MEETING_COST_SHOWCASE_PROJECT.authorUsername,
    display_name: MEETING_COST_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Meeting and productivity tools submitted through PathForge source runs.',
    role: 'user',
    created_at: '2026-06-03T23:17:21Z',
    updated_at: MEETING_COST_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222219',
    username: WORD_LADDER_SPRINT_SHOWCASE_PROJECT.authorUsername,
    display_name: WORD_LADDER_SPRINT_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Playable word and mobile game builds submitted through PathForge source runs.',
    role: 'user',
    created_at: WORD_LADDER_SPRINT_SHOWCASE_PROJECT.createdAt,
    updated_at: WORD_LADDER_SPRINT_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222220',
    username: PUZZLE_BOX_ESCAPE_SHOWCASE_PROJECT.authorUsername,
    display_name: PUZZLE_BOX_ESCAPE_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Puzzle and browser-game builds submitted through PathForge source runs.',
    role: 'user',
    created_at: PUZZLE_BOX_ESCAPE_SHOWCASE_PROJECT.createdAt,
    updated_at: PUZZLE_BOX_ESCAPE_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222221',
    username: POCKET_RALLY_SHOWCASE_PROJECT.authorUsername,
    display_name: POCKET_RALLY_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Racing and arcade browser-game builds submitted through PathForge source runs.',
    role: 'user',
    created_at: POCKET_RALLY_SHOWCASE_PROJECT.createdAt,
    updated_at: POCKET_RALLY_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    username: TRIP_PACKING_SHOWCASE_PROJECT.authorUsername,
    display_name: TRIP_PACKING_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Travel and productivity tools submitted through PathForge source runs.',
    role: 'user',
    created_at: TRIP_PACKING_SHOWCASE_PROJECT.createdAt,
    updated_at: TRIP_PACKING_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222223',
    username: FLASHCARD_CRAM_SHOWCASE_PROJECT.authorUsername,
    display_name: FLASHCARD_CRAM_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Study and education tools submitted through PathForge source runs.',
    role: 'user',
    created_at: FLASHCARD_CRAM_SHOWCASE_PROJECT.createdAt,
    updated_at: FLASHCARD_CRAM_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222224',
    username: FOLLOW_UP_CRM_SHOWCASE_PROJECT.authorUsername,
    display_name: FOLLOW_UP_CRM_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Sales, follow-up, and solo-operator tools submitted through PathForge source runs.',
    role: 'user',
    created_at: FOLLOW_UP_CRM_SHOWCASE_PROJECT.createdAt,
    updated_at: FOLLOW_UP_CRM_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222225',
    username: REACTION_TRAINER_SHOWCASE_PROJECT.authorUsername,
    display_name: REACTION_TRAINER_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Fast browser-game and reaction trainer builds submitted through PathForge source runs.',
    role: 'user',
    created_at: REACTION_TRAINER_SHOWCASE_PROJECT.createdAt,
    updated_at: REACTION_TRAINER_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: '22222222-2222-2222-2222-222222222226',
    username: LANE_DEFENSE_SHOWCASE_PROJECT.authorUsername,
    display_name: LANE_DEFENSE_SHOWCASE_PROJECT.authorDisplayName,
    avatar_url: null,
    bio: 'Tiny strategy game builds submitted through PathForge source runs.',
    role: 'user',
    created_at: LANE_DEFENSE_SHOWCASE_PROJECT.createdAt,
    updated_at: LANE_DEFENSE_SHOWCASE_PROJECT.updatedAt,
  },
  ...PENDING_SOURCE_RUN_SHOWCASE_PROJECTS.map((project, index) => ({
    id: pendingSourceRunProfileId(index),
    username: project.authorUsername,
    display_name: project.authorDisplayName,
    avatar_url: null,
    bio: 'Prepared source-run project author profile.',
    role: 'user' as const,
    created_at: project.createdAt,
    updated_at: project.updatedAt,
  })),
]

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Finance & Accounting', slug: 'finance', description: 'Budgeting, forecasting, analysis, and financial planning', icon: '💰', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-2', name: 'Marketing & Sales', slug: 'marketing', description: 'Campaigns, content strategy, lead generation, and outreach', icon: '📢', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-3', name: 'Writing & Content', slug: 'writing', description: 'Blog posts, emails, copy, and creative writing', icon: '✍️', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-4', name: 'Coding & Development', slug: 'coding', description: 'Code generation, debugging, architecture, and documentation', icon: '💻', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-5', name: 'Design & Creative', slug: 'design', description: 'UI/UX, branding, image generation, and visual design', icon: '🎨', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-6', name: 'Education & Learning', slug: 'education', description: 'Study plans, explanations, tutoring, and course creation', icon: '📚', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-7', name: 'Productivity', slug: 'productivity', description: 'Task management, meetings, workflows, and automation', icon: '⚡', prompt_count: 1, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-8', name: 'Data & Analysis', slug: 'data', description: 'Data visualization, surveys, reporting, and insights', icon: '📊', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-9', name: 'Business Strategy', slug: 'strategy', description: 'SWOT analysis, business plans, market research, and OKRs', icon: '🎯', prompt_count: 0, created_at: '2026-03-01T00:00:00Z' },
  { id: 'cat-10', name: 'Personal & Fun', slug: 'personal', description: 'Games, experiments, creative demos, and playful AI builds', icon: '🎮', prompt_count: 1, created_at: '2026-03-01T00:00:00Z' },
]

function stepsForShowcase(project: PreparedShowcaseProject): PromptStep[] {
  return project.steps.map((step) => ({
    id: step.id,
    prompt_id: project.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: project.createdAt,
  }))
}

export const mockSteps: PromptStep[] = [
  {
    id: 'step-snake-gpt55-pro-oneshot-1',
    prompt_id: SNAKE_PROJECT_ID,
    step_number: 1,
    title: 'One-sentence Snake game build',
    content: 'Make me a playable Snake game as a single self-contained HTML file.',
    result_content: 'ChatGPT returned a self-contained HTML file for a playable Snake game. The response artifact is mounted directly at the top of the demo page, with the exact response package collapsed below it for verification.',
    description: 'One plain prompt that generated the playable browser game',
    created_at: '2026-05-23T18:00:00Z',
  },
  ...HP_10BII_SHOWCASE_PROJECT.steps.map((step) => ({
    id: step.id,
    prompt_id: HP_10BII_SHOWCASE_PROJECT.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: HP_10BII_SHOWCASE_PROJECT.createdAt,
  })),
  ...TIC_TAC_TOE_SHOWCASE_PROJECT.steps.map((step) => ({
    id: step.id,
    prompt_id: TIC_TAC_TOE_SHOWCASE_PROJECT.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: TIC_TAC_TOE_SHOWCASE_PROJECT.createdAt,
  })),
  ...POMODORO_TIMER_SHOWCASE_PROJECT.steps.map((step) => ({
    id: step.id,
    prompt_id: POMODORO_TIMER_SHOWCASE_PROJECT.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: POMODORO_TIMER_SHOWCASE_PROJECT.createdAt,
  })),
  ...WEEKEND_CHECKLIST_SHOWCASE_PROJECT.steps.map((step) => ({
    id: step.id,
    prompt_id: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.createdAt,
  })),
  ...NEON_BLOCK_PATROL_SHOWCASE_PROJECT.steps.map((step) => ({
    id: step.id,
    prompt_id: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.createdAt,
  })),
  ...SWISH_CITY_SHOWCASE_PROJECT.steps.map((step) => ({
    id: step.id,
    prompt_id: SWISH_CITY_SHOWCASE_PROJECT.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: SWISH_CITY_SHOWCASE_PROJECT.createdAt,
  })),
  ...MEETING_COST_SHOWCASE_PROJECT.steps.map((step) => ({
    id: step.id,
    prompt_id: MEETING_COST_SHOWCASE_PROJECT.id,
    step_number: step.stepNumber,
    title: step.title,
    content: step.content,
    result_content: step.resultContent,
    description: step.description,
    created_at: MEETING_COST_SHOWCASE_PROJECT.createdAt,
  })),
  ...stepsForShowcase(WORD_LADDER_SPRINT_SHOWCASE_PROJECT),
  ...stepsForShowcase(PUZZLE_BOX_ESCAPE_SHOWCASE_PROJECT),
  ...stepsForShowcase(POCKET_RALLY_SHOWCASE_PROJECT),
  ...stepsForShowcase(TRIP_PACKING_SHOWCASE_PROJECT),
  ...stepsForShowcase(FLASHCARD_CRAM_SHOWCASE_PROJECT),
  ...stepsForShowcase(FOLLOW_UP_CRM_SHOWCASE_PROJECT),
  ...stepsForShowcase(REACTION_TRAINER_SHOWCASE_PROJECT),
  ...stepsForShowcase(LANE_DEFENSE_SHOWCASE_PROJECT),
  ...PENDING_SOURCE_RUN_SHOWCASE_PROJECTS.flatMap(stepsForShowcase),
]

function promptForShowcase(project: PreparedShowcaseProject, authorId: string): Prompt {
  return {
    id: project.id,
    title: project.title,
    description: project.description,
    content: project.content,
    result_content: project.resultContent,
    category_id: project.mockCategoryId,
    difficulty: project.difficulty,
    model_used: project.modelUsed,
    model_recommendation: project.modelRecommendation,
    tools_used: project.toolsUsed,
    tags: project.tags,
    status: 'approved',
    author_id: authorId,
    vote_count: 0,
    bookmark_count: 0,
    prompt_family_id: project.promptFamilyId ?? null,
    created_at: project.createdAt,
    updated_at: project.updatedAt,
  }
}

export const mockPrompts: Prompt[] = [
  {
    id: SNAKE_PROJECT_ID,
    title: 'Playable Snake Game - GPT 5.5 Pro One-Shot',
    description: 'A first-taste demo path: one plain sentence produced a playable Snake game, with the final artifact embedded at the top and the captured response package below it.',
    content: 'This is the simplest approved PathForge seed: one normal user prompt, one captured model response, one playable result. It exists to show how a finished artifact, exact prompt, exact response package, attachments, and verification can live together on a project page.',
    result_content: 'A playable Snake game embedded directly on the page. The response package includes the one-sentence prompt, the generated HTML artifact, verification screenshots, and a collapsed exact-response drawer.',
    category_id: 'cat-10',
    difficulty: 'beginner',
    model_used: null,
    model_recommendation: 'Latest 5.5 / Extended Pro',
    tools_used: ['ChatGPT', 'GPT 5.5 Pro', 'HTML', 'Browser'],
    tags: ['snake', 'game', 'arcade', 'html', 'one-shot', 'playable artifact', 'personal fun', 'token maxing', 'AI paralysis'],
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222211',
    vote_count: 0,
    bookmark_count: 0,
    created_at: '2026-05-23T18:00:00Z',
    updated_at: '2026-05-24T16:15:00Z',
  },
  {
    id: HP_10BII_SHOWCASE_PROJECT.id,
    title: HP_10BII_SHOWCASE_PROJECT.title,
    description: HP_10BII_SHOWCASE_PROJECT.description,
    content: HP_10BII_SHOWCASE_PROJECT.content,
    result_content: HP_10BII_SHOWCASE_PROJECT.resultContent,
    category_id: HP_10BII_SHOWCASE_PROJECT.mockCategoryId,
    difficulty: HP_10BII_SHOWCASE_PROJECT.difficulty,
    model_used: HP_10BII_SHOWCASE_PROJECT.modelUsed,
    model_recommendation: HP_10BII_SHOWCASE_PROJECT.modelRecommendation,
    tools_used: HP_10BII_SHOWCASE_PROJECT.toolsUsed,
    tags: HP_10BII_SHOWCASE_PROJECT.tags,
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222212',
    vote_count: 0,
    bookmark_count: 0,
    created_at: HP_10BII_SHOWCASE_PROJECT.createdAt,
    updated_at: HP_10BII_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: TIC_TAC_TOE_SHOWCASE_PROJECT.id,
    title: TIC_TAC_TOE_SHOWCASE_PROJECT.title,
    description: TIC_TAC_TOE_SHOWCASE_PROJECT.description,
    content: TIC_TAC_TOE_SHOWCASE_PROJECT.content,
    result_content: TIC_TAC_TOE_SHOWCASE_PROJECT.resultContent,
    category_id: TIC_TAC_TOE_SHOWCASE_PROJECT.mockCategoryId,
    difficulty: TIC_TAC_TOE_SHOWCASE_PROJECT.difficulty,
    model_used: TIC_TAC_TOE_SHOWCASE_PROJECT.modelUsed,
    model_recommendation: TIC_TAC_TOE_SHOWCASE_PROJECT.modelRecommendation,
    tools_used: TIC_TAC_TOE_SHOWCASE_PROJECT.toolsUsed,
    tags: TIC_TAC_TOE_SHOWCASE_PROJECT.tags,
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222213',
    vote_count: 0,
    bookmark_count: 0,
    created_at: TIC_TAC_TOE_SHOWCASE_PROJECT.createdAt,
    updated_at: TIC_TAC_TOE_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: POMODORO_TIMER_SHOWCASE_PROJECT.id,
    title: POMODORO_TIMER_SHOWCASE_PROJECT.title,
    description: POMODORO_TIMER_SHOWCASE_PROJECT.description,
    content: POMODORO_TIMER_SHOWCASE_PROJECT.content,
    result_content: POMODORO_TIMER_SHOWCASE_PROJECT.resultContent,
    category_id: POMODORO_TIMER_SHOWCASE_PROJECT.mockCategoryId,
    difficulty: POMODORO_TIMER_SHOWCASE_PROJECT.difficulty,
    model_used: POMODORO_TIMER_SHOWCASE_PROJECT.modelUsed,
    model_recommendation: POMODORO_TIMER_SHOWCASE_PROJECT.modelRecommendation,
    tools_used: POMODORO_TIMER_SHOWCASE_PROJECT.toolsUsed,
    tags: POMODORO_TIMER_SHOWCASE_PROJECT.tags,
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222214',
    vote_count: 0,
    bookmark_count: 0,
    created_at: POMODORO_TIMER_SHOWCASE_PROJECT.createdAt,
    updated_at: POMODORO_TIMER_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.id,
    title: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.title,
    description: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.description,
    content: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.content,
    result_content: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.resultContent,
    category_id: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.mockCategoryId,
    difficulty: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.difficulty,
    model_used: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.modelUsed,
    model_recommendation: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.modelRecommendation,
    tools_used: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.toolsUsed,
    tags: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.tags,
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222215',
    vote_count: 0,
    bookmark_count: 0,
    created_at: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.createdAt,
    updated_at: WEEKEND_CHECKLIST_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.id,
    title: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.title,
    description: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.description,
    content: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.content,
    result_content: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.resultContent,
    category_id: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.mockCategoryId,
    difficulty: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.difficulty,
    model_used: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.modelUsed,
    model_recommendation: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.modelRecommendation,
    tools_used: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.toolsUsed,
    tags: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.tags,
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222216',
    vote_count: 0,
    bookmark_count: 0,
    created_at: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.createdAt,
    updated_at: NEON_BLOCK_PATROL_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: SWISH_CITY_SHOWCASE_PROJECT.id,
    title: SWISH_CITY_SHOWCASE_PROJECT.title,
    description: SWISH_CITY_SHOWCASE_PROJECT.description,
    content: SWISH_CITY_SHOWCASE_PROJECT.content,
    result_content: SWISH_CITY_SHOWCASE_PROJECT.resultContent,
    category_id: SWISH_CITY_SHOWCASE_PROJECT.mockCategoryId,
    difficulty: SWISH_CITY_SHOWCASE_PROJECT.difficulty,
    model_used: SWISH_CITY_SHOWCASE_PROJECT.modelUsed,
    model_recommendation: SWISH_CITY_SHOWCASE_PROJECT.modelRecommendation,
    tools_used: SWISH_CITY_SHOWCASE_PROJECT.toolsUsed,
    tags: SWISH_CITY_SHOWCASE_PROJECT.tags,
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222217',
    vote_count: 0,
    bookmark_count: 0,
    created_at: SWISH_CITY_SHOWCASE_PROJECT.createdAt,
    updated_at: SWISH_CITY_SHOWCASE_PROJECT.updatedAt,
  },
  {
    id: MEETING_COST_SHOWCASE_PROJECT.id,
    title: MEETING_COST_SHOWCASE_PROJECT.title,
    description: MEETING_COST_SHOWCASE_PROJECT.description,
    content: MEETING_COST_SHOWCASE_PROJECT.content,
    result_content: MEETING_COST_SHOWCASE_PROJECT.resultContent,
    category_id: MEETING_COST_SHOWCASE_PROJECT.mockCategoryId,
    difficulty: MEETING_COST_SHOWCASE_PROJECT.difficulty,
    model_used: MEETING_COST_SHOWCASE_PROJECT.modelUsed,
    model_recommendation: MEETING_COST_SHOWCASE_PROJECT.modelRecommendation,
    tools_used: MEETING_COST_SHOWCASE_PROJECT.toolsUsed,
    tags: MEETING_COST_SHOWCASE_PROJECT.tags,
    status: 'approved',
    author_id: '22222222-2222-2222-2222-222222222218',
    vote_count: 0,
    bookmark_count: 0,
    created_at: MEETING_COST_SHOWCASE_PROJECT.createdAt,
    updated_at: MEETING_COST_SHOWCASE_PROJECT.updatedAt,
  },
  promptForShowcase(WORD_LADDER_SPRINT_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222219'),
  promptForShowcase(PUZZLE_BOX_ESCAPE_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222220'),
  promptForShowcase(POCKET_RALLY_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222221'),
  promptForShowcase(TRIP_PACKING_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222222'),
  promptForShowcase(FLASHCARD_CRAM_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222223'),
  promptForShowcase(FOLLOW_UP_CRM_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222224'),
  promptForShowcase(REACTION_TRAINER_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222225'),
  promptForShowcase(LANE_DEFENSE_SHOWCASE_PROJECT, '22222222-2222-2222-2222-222222222226'),
  ...PENDING_SOURCE_RUN_SHOWCASE_PROJECTS.map((project, index) => promptForShowcase(project, pendingSourceRunProfileId(index))),
]

export const mockSuggestions: SuggestionWithRelations[] = []

export const mockSuggestionResponses: SuggestionResponse[] = []

export const mockBuildRequests: BuildRequestWithRelations[] = []
