import type { PreparedShowcaseProject } from './prepared-showcase-projects'
import {
  TINY_TRAIN_DISPATCHER_PROJECT_ID,
  BREAKROOM_SNACK_RESTOCK_PROJECT_ID,
  PORCH_LIGHT_MOTH_MAZE_PROJECT_ID,
  PANTRY_SHELF_LIFE_RESCUE_PROJECT_ID,
  MINI_HARBOR_TUGBOAT_PROJECT_ID,
  TINY_FARMERS_MARKET_PROJECT_ID,
  ROOMMATE_CHORE_DRAFT_PROJECT_ID,
  POCKET_PIRATE_MAP_PROJECT_ID,
  POTLUCK_TABLE_PLANNER_PROJECT_ID,
  RAINY_WINDOW_CAFE_RUSH_PROJECT_ID,
  LUNCHBOX_CONVEYOR_SORTER_PROJECT_ID,
  PORCH_PLANT_WATERING_PROJECT_ID,
  SHARED_ERRAND_ROUTE_PROJECT_ID,
  MINI_GOLF_WINDMILL_PROJECT_ID,
  LEFTOVER_DINNER_BOARD_PROJECT_ID,
  TINY_LOOP_SEQUENCER_PROJECT_ID,
  GARAGE_SALE_TAGS_PROJECT_ID,
  MICRO_DUNGEON_ROUTE_PROJECT_ID,
  BAKE_SALE_MARGIN_PROJECT_ID,
  STAR_MAP_SCAVENGER_PROJECT_ID,
} from './featured-projects'

type PendingSourceRunDescriptor = {
  projectId: string
  sourceRunId: string
  href: string
  title: string
  description: string
  content: string
  resultContent: string
  categorySlug: string
  mockCategoryId: string
  difficulty: 'beginner'
  modelUsed: string
  modelRecommendation: string
  promptFamilyId?: string
  toolsUsed: string[]
  tags: string[]
  artifactPath: string
  sourceUrl: string
  authorDisplayName: string
  authorUsername: string
  createdAt: string
  updatedAt: string
  prompts: string[]
}

function buildPendingSourceRunProject(input: PendingSourceRunDescriptor): PreparedShowcaseProject {
  return {
    id: input.projectId,
    sourceRunId: input.sourceRunId,
    href: input.href,
    title: input.title,
    description: input.description,
    content: input.content,
    resultContent: input.resultContent,
    categorySlug: input.categorySlug,
    mockCategoryId: input.mockCategoryId,
    difficulty: input.difficulty,
    modelUsed: input.modelUsed,
    modelRecommendation: input.modelRecommendation,
    promptFamilyId: input.promptFamilyId,
    toolsUsed: input.toolsUsed,
    tags: input.tags,
    artifactPath: input.artifactPath,
    sourceUrl: input.sourceUrl,
    authorDisplayName: input.authorDisplayName,
    authorUsername: input.authorUsername,
    createdAt: input.createdAt,
    updatedAt: input.updatedAt,
    steps: input.prompts.map((prompt, index) => ({
      id: `${input.projectId}-step-${index + 1}`,
      stepNumber: index + 1,
      title: index === 0 ? 'Start the build' : `Refine the build ${index + 1}`,
      content: prompt,
      resultContent: '',
      description: index === input.prompts.length - 1
        ? 'Final response package that produced the mounted public artifact.'
        : 'Captured source-run prompt preserved before its response package.',
    })),
  }
}

export const TINY_TRAIN_DISPATCHER_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: TINY_TRAIN_DISPATCHER_PROJECT_ID,
  sourceRunId: "90bf62c0-ae89-4b03-95fd-5d1ad0f29f9f",
  href: "/tiny-train-platform-dispatcher-demo",
  title: "Tiny Train Platform Dispatcher",
  description: "Single-file train platform dispatcher game where players route arriving trains to three platforms before timers expire.",
  content: "Maren Ellis used Claude to build Tiny Train Platform Dispatcher through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "A compact station-control game: incoming trains spawn with TTL bars, players route them to three timed platforms, score is awarded for fast dispatch, missed trains reduce score, level escalates after time, and five misses closes the station.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "Sonnet 4.6 Max (visible Claude composer model label)",
  modelRecommendation: "Sonnet 4.6 Max (visible Claude composer model label)",
  toolsUsed: ["Claude in logged-in Chrome session","local static verification server","Chrome browser verification"],
  tags: ["trains","dispatcher","time-management","simulation","single-file-html","keyboard","mobile","source-run"],
  artifactPath: "/artifacts/tiny-train-platform-dispatcher-claude.html",
  sourceUrl: "https://claude.ai/chat/77f9eb29-e596-43ed-9080-baeafce15e7e",
  authorDisplayName: "Maren Ellis",
  authorUsername: "MarenEllis",
  createdAt: "2026-06-05T07:40:00-04:00",
  updatedAt: "2026-06-05T12:01:18.909Z",
  prompts: [
    "Build me a tiny train platform dispatcher as a single-file HTML game: it should be easy to understand fast, let me route arriving trains into platforms under time pressure, and run with no external assets.",
    "The preview didn’t load here; please give me the complete single-file HTML/CSS/JS in a code block instead, keeping the train selection and platform routing rules you described.",
    "This is close, but the file still loads Google Fonts. Remove every external resource so it works fully offline, keep it as one HTML file, and preserve the current dispatcher gameplay.",
    "The offline artifact looks like the right version, but I need the complete source pasted inline too. Please paste the full current offline HTML in one code block, unchanged from the artifact version.",
    "I tested the saved file and it only works by clicking; the final needs keyboard support too, and the 5-column HUD looks tight for phones. Add keyboard shortcuts for selecting arrivals and assigning platforms, keep pointer/touch clicks, and make the layout stack cleanly at 390px with no horizontal overflow. Still one offline HTML file."
  ],
})

export const BREAKROOM_SNACK_RESTOCK_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: BREAKROOM_SNACK_RESTOCK_PROJECT_ID,
  sourceRunId: "0e244880-4d58-40f7-b865-d056d9f4334f",
  href: "/breakroom-snack-restock-planner-demo",
  title: "Breakroom Snack Restock Planner",
  description: "A one-file office breakroom restock planner that starts with sample snacks and teammate preferences, ranks purchase priority, estimates spend, supports editing and handoff, and persists locally.",
  content: "Casey Luo used Gemini to build Breakroom Snack Restock Planner through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "A browser-based breakroom snack restock planner with sample inventory and preferences, restock scoring, estimated spend, add/edit/remove workflows, local persistence, and copy/export/print handoff.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Flash",
  modelRecommendation: "Flash",
  toolsUsed: ["Gemini web in Chrome","local browser verification"],
  tags: ["breakroom","snack restock","inventory","team preferences","office ops","single-file HTML","localStorage","export","print","source-run"],
  artifactPath: "/artifacts/breakroom-snack-restock-planner-gemini.html",
  sourceUrl: "https://gemini.google.com/app/f23df8e88c1bb20a",
  authorDisplayName: "Casey Luo",
  authorUsername: "CaseyLuo",
  createdAt: "2026-06-05T11:48:17.438Z",
  updatedAt: "2026-06-05T11:51:22.232Z",
  prompts: [
    "Could you make a single-file HTML planner for our office breakroom snack restock that starts with a few sample items and teammate preferences, then shows what to buy first and a rough spend so I can use it quickly?",
    "The first version has the basics, but I need a clean handoff once the list is ready. Add copy, export, and print controls for the restock order, and let me edit existing rows without deleting them first.",
    "The handoff buttons help, but the teammate preference section is still just a static note. Let me add, edit, and remove teammate preferences, and have those requests influence the restock priority score.",
    "This is getting close. I want the whole board to survive reloads, including teammate preferences and edits, and I want a one-click restore of the sample inventory/preferences so someone can demo it without setup.",
    "Since that last reply was just a check, give me the final consolidated single-file HTML now: keep the edit/add/remove flows, copy/export/print handoff, persistence/restore demo data, and make the 390px mobile layout avoid page-level horizontal scrolling.",
    "I tested the final file in a 390px-wide harness and the document still has page-level horizontal overflow, with scrollWidth around 558px. Fix that without removing the table data or handoff controls; the table can scroll inside its own container, but the document and body width need to stay at 390px."
  ],
})

export const PORCH_LIGHT_MOTH_MAZE_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: PORCH_LIGHT_MOTH_MAZE_PROJECT_ID,
  sourceRunId: "a858d84f-4280-4ecf-aec5-8480359abe54",
  href: "/porch-light-moth-maze-demo",
  title: "Porch Light Moth Maze",
  description: "A self-contained browser game where players steer a moth through porch-light maze corridors, collect nectar, avoid bright bulb pull, choose difficulty levels, and replay for timer bonuses.",
  content: "Blair Nolan used ChatGPT to build Porch Light Moth Maze through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Playable one-file porch-light moth maze game with difficulty selection, timer bonus, keyboard/mouse/touch controls, and replay scorecard.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  modelRecommendation: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  toolsUsed: ["ChatGPT web in Chrome","single-file HTML","Canvas API","localStorage"],
  tags: ["game","maze","canvas","keyboard","touch","mouse","localStorage","mobile","source-run"],
  artifactPath: "/artifacts/porch-light-moth-maze-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a22b5b4-3730-83ea-8df5-0fe61982046b",
  authorDisplayName: "Blair Nolan",
  authorUsername: "BlairNolan",
  createdAt: "2026-06-05T11:24:00Z",
  updatedAt: "2026-06-05T11:53:21Z",
  prompts: [
    "Can you make a one-file HTML game where I steer a moth through a porch-light maze without getting trapped by the brightest bulbs?",
    "The first version runs, but the maze feels more like an open arena. Make it feel more maze-like with clearer wall corridors, add a real mouse/touch drag steering option in addition to the buttons, and keep it one offline HTML file.",
    "This is closer. The path is readable, but once you finish it there is not much reason to replay. Add a small Easy / Porch / Storm level select, a timer bonus that makes repeat attempts matter, and keep the start and replay flow clear.",
    "On a phone-sized viewport this is likely to get cramped with the five HUD boxes and level buttons. Tighten the mobile layout for 390px screens: no horizontal scrolling, buttons stay tappable, the canvas should fit above the controls, and keep everything inline/offline.",
    "This passes the narrow layout check. For the final version, make the end and replay screen more useful: show level, time, timer bonus, nectar collected, and best score; add Enter/Space replay plus 1/2/3 level shortcuts; keep the 390px no-overflow and offline single-file constraints."
  ],
})

export const PANTRY_SHELF_LIFE_RESCUE_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: PANTRY_SHELF_LIFE_RESCUE_PROJECT_ID,
  sourceRunId: "61ea4cdf-d984-4195-be6c-c21db7e2ad85",
  href: "/pantry-shelf-life-rescue-planner-demo",
  title: "Pantry Shelf-Life Rescue Planner",
  description: "A one-file pantry and fridge rescue planner that tracks expiring items, portions, locations, constraints, use-now meal combos, saved inventory, and handoff controls.",
  content: "Morgan Vale used Gemini to build Pantry Shelf-Life Rescue Planner through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Self-contained HTML planner for pantry/fridge shelf-life rescue planning. The final version lets a user load sample inventory, add items with location/days/portions/tags, save inventory locally, generate use-now meal combos, and copy/print/export/import handoff data.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Flash",
  modelRecommendation: "Flash",
  toolsUsed: ["Gemini web in Chrome","Flash mode","single-file HTML","localStorage"],
  tags: ["pantry","food waste","meal planning","home planning","localStorage","single-file HTML","source-run"],
  artifactPath: "/artifacts/pantry-shelf-life-rescue-gemini.html",
  sourceUrl: "https://gemini.google.com/app/161783fc2816f660",
  authorDisplayName: "Morgan Vale",
  authorUsername: "MorganVale",
  createdAt: "2026-06-05T10:38:00Z",
  updatedAt: "2026-06-05T10:49:55Z",
  prompts: [
    "I keep discovering cans and fridge odds-and-ends right before they expire; can you make me a single HTML file that turns a pantry/fridge list into a practical use-today rescue plan?",
    "This is a good start, but I need it to handle structured entries instead of guessing from a notes box. Add fields for item, location, days until expiration, portions, and constraint tags, then save the inventory in localStorage.",
    "The saved inventory helps, but the plan still feels like priority buckets more than actual meals. Add a use-now section that groups expiring items into 2 or 3 simple meal/combo suggestions and make the suggestions respect tags like vegetarian, dairy-free, no oven, or quick.",
    "This is useful now, but I need a way to hand it off. Add buttons to copy the current rescue plan, print a clean kitchen-friendly version, export the inventory/plan as a file, and import a saved inventory JSON back in.",
    "Before I use this on my phone, tighten the layout so there is no page-level horizontal overflow around 390px wide, keep any inventory table scrolling inside its own box, make the copy/export/print controls easy to test, remove any external assets, and add a small sample-inventory button for a quick demo."
  ],
})

export const MINI_HARBOR_TUGBOAT_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: MINI_HARBOR_TUGBOAT_PROJECT_ID,
  sourceRunId: "89c291ed-41fc-4e6b-ae1a-c7da9e89427b",
  href: "/mini-harbor-tugboat-switcher-demo",
  title: "Mini Harbor Tugboat Switcher",
  description: "A self-contained canvas game where players switch harbor lanes so little colored tugboats reach matching docks, with keyboard/touch controls, a short result loop, and a locally saved best score.",
  content: "Sasha Kim used ChatGPT to build Mini Harbor Tugboat Switcher through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Playable local HTML game; route tugboats through switches into matching colored docks.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  modelRecommendation: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  toolsUsed: ["ChatGPT web in Chrome","single-file HTML","Canvas API","localStorage"],
  tags: ["game","puzzle","canvas","keyboard","touch","localStorage","harbor","source-run"],
  artifactPath: "/artifacts/mini-harbor-tugboat-switcher-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a22a894-0168-83ea-8285-0118daa7c79f",
  authorDisplayName: "Sasha Kim",
  authorUsername: "SashaKim",
  createdAt: "2026-06-05T10:52:16.583Z",
  updatedAt: "2026-06-05T11:05:16.583Z",
  prompts: [
    "My kid keeps asking about harbor boats; build me a tiny browser game where little tugboats hit switchable water lanes and have to dock at the matching pier. I'd like one HTML file I can open locally.",
    "The harbor idea is there, but I can only tap the switches. Add keyboard controls so keys 1-6 cycle the six switches, and show that control hint without making the page feel crowded.",
    "Can you give me the whole updated HTML file instead of snippets, with the 1-6 shortcuts already wired in? Also add a best score that saves locally after each harbor run.",
    "This is closer, but the ending still feels like a little canvas message. Add a clear short result panel with final score, docked count, best score, and a Play Again button so the loop feels finished.",
    "The result loop helps. For the first 15 seconds, make the board easier to read: label the switches 1-6 on the water, show the next tug color before it launches, and add a short start panel with the goal. Please send the full HTML again.",
    "One last pass before I save it for review: make the file fully offline with no external resources, avoid page-level horizontal overflow on a 390px phone, and keep touch/mouse, 1-6 keyboard controls, the result panel, and local best score working. Send the complete final HTML."
  ],
})

export const TINY_FARMERS_MARKET_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: TINY_FARMERS_MARKET_PROJECT_ID,
  sourceRunId: "8f0bf0c7-e3fa-4e0b-86f7-d9cfa4e77cef",
  href: "/tiny-farmers-market-booth-simulator-demo",
  title: "Tiny Farmers Market Booth Simulator",
  description: "A playful offline farmers market booth simulator where the user picks produce, prices stock, runs market hours, compares goals, saves history, uses presets, and copies a booth report.",
  content: "Finn Parker used Claude to build Tiny Farmers Market Booth Simulator through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Single-file offline HTML farmers market booth simulator with five captured Claude-generated versions.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Sonnet 4.6 Max (visible Claude composer model label)",
  modelRecommendation: "Sonnet 4.6 Max (visible Claude composer model label)",
  toolsUsed: ["Claude web","Chrome","local browser verification"],
  tags: ["farmers market","simulator","pricing","localStorage","mobile","offline","playful productivity","source-run"],
  artifactPath: "/artifacts/tiny-farmers-market-booth-claude.html",
  sourceUrl: "https://claude.ai/chat/0c68b5be-8ca9-47e3-9087-04668db8e9d1",
  authorDisplayName: "Finn Parker",
  authorUsername: "FinnParker",
  createdAt: "2026-06-05T09:41:00Z",
  updatedAt: "2026-06-05T10:33:38.957Z",
  prompts: [
    "I keep thinking a tiny farmers market booth would make a nice little browser sim: pick today's produce, set prices, and see if the booth makes money before the market closes. Can you make it as one complete HTML file and paste the full code here so I can save it?",
    "This is fun, but I noticed the file still pulls Google Fonts and I want it to work completely offline. Can you remove any external resources, keep the same cozy feel with system fonts, and add one setup choice for the booth goal — profit, sell-through, or freshness — that changes the end-of-day grade? Please paste the full updated HTML.",
    "This is getting useful as a little planning toy. I want to compare a few booth attempts instead of losing each run after the results screen. Add a saved market-day history using localStorage with the goal, weather, profit, sell-through, and grade for each completed day, plus a clear-history button. Keep it offline and paste the full updated HTML.",
    "One thing I would worry about before using this on my phone: the setup table may get cramped once quantity and price inputs are visible. Can you make the setup screen phone-first with produce cards or stacked controls instead of a wide table, keep the desktop view tidy, and make sure the page itself will not horizontally overflow around 390px wide? Full updated HTML please.",
    "Last thing I would add: make it easier to replay or share a finished booth day. Add a few setup presets like balanced Saturday, rainy budget table, and premium berries/herbs, and add a copyable booth report on the results screen with the goal, weather, profit, sell-through, grade, and best/worst items. Keep it all offline with no external resources and paste the full updated HTML.",
    "I ran a 390px iframe check and found a real mobile overflow: the header history button pushes the body to about 428px wide even though html overflow is hidden. Please fix the mobile header/meta layout so both document and body stay within 390px without clipping the History button or count, keep all existing features, and paste the full corrected HTML."
  ],
})

export const ROOMMATE_CHORE_DRAFT_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: ROOMMATE_CHORE_DRAFT_PROJECT_ID,
  sourceRunId: "d224897c-0aab-4a01-88d6-a0e3bd5f47d9",
  href: "/roommate-chore-draft-board-demo",
  title: "Roommate Chore Draft Board",
  description: "A self-contained roommate chore draft board that adds roommates and chores, runs a snake-style assignment draft, balances effort-point load totals, autosaves locally, copies/shares the final plan, and prints a clean chore plan.",
  content: "Leah Brooks used Gemini to build Roommate Chore Draft Board through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Final artifact is a self-contained roommate chore draft board with editable roommates and chores, snake-style turn order, effort-point load totals, localStorage autosave, reset controls, copy/share summary, and print-friendly final plan.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Flash (visible Gemini mode picker; exact backend version not exposed)",
  modelRecommendation: "Flash (visible Gemini mode picker; exact backend version not exposed)",
  toolsUsed: ["Gemini web","Chrome","HTML","CSS","JavaScript","localStorage"],
  tags: ["roommates","chores","home coordination","draft board","snake draft","local storage","printable plan","mobile tool","source-run"],
  artifactPath: "/artifacts/roommate-chore-draft-board-gemini.html",
  sourceUrl: "https://gemini.google.com/app/41ebf33c66736e90",
  authorDisplayName: "Leah Brooks",
  authorUsername: "LeahBrooks",
  createdAt: "2026-06-05T09:43:00Z",
  updatedAt: "2026-06-05T09:56:00Z",
  prompts: [
    "My apartment needs a less awkward way to split chores this week. Build a one-page HTML chore draft board where we can add roommates/chores, draft assignments, and print the final plan.",
    "This is useful, but it still feels like a manual selector. Can you make it run like an actual chore draft with a visible turn order and snake-style next picker so we don't have to remember whose turn it is?",
    "I forgot the part where we might close the laptop halfway through. Add localStorage autosave, a clear/reset control, and a small last-saved status line without making the printed plan noisy.",
    "The draft is better, but it treats bathroom deep clean and taking out trash like the same size job. Add simple effort points or time estimates to chores and show each roommate's total load so we can draft toward fairness.",
    "Can you put those effort points into the actual HTML file instead of just listing an example? While you're in there, add a copy/share summary button for the final assignments and make sure the mobile layout stays usable.",
    "This is close, but I noticed the HTML pulls canvas-confetti from a CDN. Remove that external script and use a tiny built-in celebration effect or no celebration at all. Keep the effort totals, localStorage autosave, copy/share summary, print view, and mobile layout."
  ],
})

export const POCKET_PIRATE_MAP_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: POCKET_PIRATE_MAP_PROJECT_ID,
  sourceRunId: "791a6b31-90ab-42ed-ba20-2d730326bc46",
  href: "/pocket-pirate-map-decoder-demo",
  title: "Pocket Pirate Map Decoder",
  description: "A self-contained playful browser puzzle where players decode pirate-map glyphs, rotate symbols, trace routes to treasure, use score-costing hints, and replay multiple compact maps.",
  content: "Riley Dawson used ChatGPT to build Pocket Pirate Map Decoder through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "One-file HTML pirate map decoder puzzle with glyph decoding, route tracing, multiple map layouts, new-map replay, hint penalty, scoring, local best score, treasure-log summary, touch controls, keyboard shortcuts, and accessible button labels.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  modelRecommendation: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  toolsUsed: ["ChatGPT web normal lane in Chrome","HTML","CSS","JavaScript","localStorage"],
  tags: ["pirate map","decoder puzzle","browser game","route tracing","keyboard controls","touch controls","mobile-friendly","local storage","source-run"],
  artifactPath: "/artifacts/pocket-pirate-map-decoder-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a2299d6-18c0-83ea-8749-3c1d42086eb1",
  authorDisplayName: "Riley Dawson",
  authorUsername: "RileyDawson",
  createdAt: "2026-06-05T09:10:00Z",
  updatedAt: "2026-06-05T10:05:21.961Z",
  prompts: [
    "I want a pocket-size pirate map puzzle where you decode symbols and trace the route to buried treasure; can you make it as a playable HTML file I can open locally?",
    "This is fun, but the decoding part still feels a little too guided. Make the player rotate or choose the map symbols so the route only becomes obvious after solving them, and send the full updated HTML again.",
    "Now that the rotate-to-decode part works, it needs more replay value. Add three different treasure maps with different symbol clues and routes, plus a new-map button, without turning it into a big menu.",
    "The small-map idea is right, but this needs to feel good on a phone. Make the symbol buttons and route grid more touch-friendly around 390px wide, and make sure the page itself does not horizontally scroll.",
    "I forgot one thing that would make it more game-like: add a hint button that costs score, track best score in local storage, and show a short treasure-log summary when the player wins. Keep the mobile-safe layout.",
    "One last pass before I save it: remove any external URLs or resources if any slipped in, add keyboard shortcuts and accessible button labels for the main actions, and paste the complete final HTML."
  ],
})

export const POTLUCK_TABLE_PLANNER_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: POTLUCK_TABLE_PLANNER_PROJECT_ID,
  sourceRunId: "411a6260-a9d2-44d4-a150-430f598d7ebf",
  href: "/potluck-table-planner-demo",
  title: "Potluck Table Planner",
  description: "A mobile-friendly one-file potluck setup planner that tracks dishes, assignments, table zones, gaps, local saved state, and group-text/print handoff.",
  content: "Maya Reed used Gemini to build Potluck Table Planner through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Final artifact is a self-contained mobile potluck planning board with dish cards, assignments, table-zone map, gap counts, local persistence, editable rows, group-text export, and print handoff.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Flash (visible Gemini mode picker; exact backend version not exposed)",
  modelRecommendation: "Flash (visible Gemini mode picker; exact backend version not exposed)",
  toolsUsed: ["Gemini web","HTML","CSS","JavaScript","localStorage"],
  tags: ["potluck","event planning","table planner","household planning","local storage","mobile tool","source-run"],
  artifactPath: "/artifacts/potluck-table-planner-gemini.html",
  sourceUrl: "https://gemini.google.com/app/b6aa80887a4d6f7e",
  authorDisplayName: "Maya Reed",
  authorUsername: "MayaReed",
  createdAt: "2026-06-05T07:28:00Z",
  updatedAt: "2026-06-05T07:49:24Z",
  prompts: [
    "Hosting a potluck this weekend and my group text is already messy. Can you make a self-contained HTML table planner where I can add dishes, who's bringing them, category, serving/utensil needs, and see gaps at a glance? Please give me the full file in one code block.",
    "I tried the first version and it is helpful, but I would lose the plan if I closed the tab. Add local storage plus edit and delete controls for dishes, and keep it in one self-contained HTML file with the full updated code block.",
    "The saving and edit controls are what I needed. For the actual setup, though, I need to decide which table section each dish belongs on and spot missing zones fast. Add a simple table layout view with zones like mains, sides, desserts, drinks, supplies, plus clear gap warnings, still as one self-contained HTML file.",
    "This is getting close. For the night-of handoff I need a print/export summary and a copy-to-group-text version grouped by table section, and unassigned dishes should jump out before people arrive. Add those pieces while keeping local storage, editing, and no backend.",
    "Last thing: this will mostly be used on a phone while setting up. Make the mobile layout tight at about 390px wide: no page-level horizontal scrolling, table rows should become readable cards if needed, and the edit/export/share buttons should still fit. Keep the full final self-contained HTML in one code block."
  ],
})

export const RAINY_WINDOW_CAFE_RUSH_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: RAINY_WINDOW_CAFE_RUSH_PROJECT_ID,
  sourceRunId: "4a65e80b-771e-4034-8cdf-f983ce70413e",
  href: "/rainy-window-cafe-rush-demo",
  title: "Rainy Window Cafe Rush",
  description: "A self-contained rainy-window café rush browser game where players select sliding drinks, serve named customer tickets with touch or 1/2/3 shortcuts, protect combos/tips, pause safely, survive a rain-burst speed event, and chase a saved best shift.",
  content: "Quinn Walker used ChatGPT to build Rainy Window Cafe Rush through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Self-contained rainy café rush HTML game with sliding drink rail, named order tickets, customer patience/mood, touch and 1/2/3 serving, combo/tips system, localStorage best score, rain-burst rush event, pause/resume, tutorial panel, mobile ticket layout, and final/best score display.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  modelRecommendation: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  toolsUsed: ["ChatGPT web normal lane in Chrome","local headless Chrome artifact verification","HTML","CSS","JavaScript","localStorage"],
  tags: ["rainy cafe","browser game","arcade rush","playful productivity","keyboard controls","touch controls","mobile-friendly","local storage","source-run"],
  artifactPath: "/artifacts/rainy-window-cafe-rush-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a227d41-d2b4-83ea-9248-8b11cdd14f75",
  authorDisplayName: "Quinn Walker",
  authorUsername: "QuinnWalker",
  createdAt: "2026-06-05T07:39:00Z",
  updatedAt: "2026-06-05T08:29:17.212Z",
  prompts: [
    "I've got a rainy-window cafe idea in my head: can you make it as a tiny playable browser game where drinks slide in, customers get impatient, and the whole thing fits in one pasteable HTML file with no outside assets?",
    "I tried the first version and the core rush is there, but it needs to be easier to read while drinks are sliding by. Add clearer named order tickets, customer mood changes, and keyboard shortcuts 1/2/3 to serve the currently selected drink to a customer. Keep it as one complete HTML file with no outside assets.",
    "Looking at the second version, the tickets and keyboard shortcuts help, but on a phone those three customer cards are going to crowd the drink rail. Redesign the small-screen layout so the order tickets become compact horizontal targets above the rail, make the selected drink target really obvious, and keep the desktop version polished. Please return the complete updated HTML file.",
    "This is much closer after the mobile ticket pass. The game still needs a stronger reason to replay: add a combo/tips system, save the best shift score in localStorage, and add a short “rain burst” rush event that warns the player before drinks and patience speed up. Keep it as one complete no-external-assets HTML file.",
    "The combo/best-score/rain-burst layer is good, but now the shift can get hectic fast. Add a pause/resume control and a concise pre-shift tutorial panel that explains selecting a drink, serving with 1/2/3, combos, and rain bursts. Preserve the mobile ticket layout, localStorage best score, and no-external-assets rule, and return the complete updated HTML.",
    "The pause/tutorial version is the right shape. For a final pass, harden it for PathForge-style local serving: make sure the page has no horizontal overflow at 390px wide, the pause/rain-burst state cannot stack or keep timers running after game over, touch drag still works without page scrolling, and the final score/best score display is clear. Keep it one complete HTML file with no outside assets and return the final full HTML."
  ],
})

export const LUNCHBOX_CONVEYOR_SORTER_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: LUNCHBOX_CONVEYOR_SORTER_PROJECT_ID,
  sourceRunId: "58487d49-36a8-4555-b6c5-17f898fa4bde",
  href: "/lunchbox-conveyor-sorter-demo",
  title: "Lunchbox Conveyor Sorter",
  description: "A mobile-friendly browser lunchbox conveyor sorting game where players drag, tap, or use keyboard shortcuts to route sandwiches, fruit, drinks, and treats into matching lunchboxes across three lunch-rush levels.",
  content: "Ari Morgan used ChatGPT to build Lunchbox Conveyor Sorter through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Self-contained HTML lunchbox conveyor sorting game with three short levels, visible goals, score/packed/misses HUD, selected-item and target-lunchbox status, correct/wrong/missed feedback, drag/touch controls, keyboard controls, mobile-fit CSS, and no final external dependencies.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  modelRecommendation: "ChatGPT Instant visible composer setting; assistant message nodes exposed gpt-5-5-thinking",
  toolsUsed: ["ChatGPT web normal lane in Chrome","local static server","headless Chrome CDP mobile verification"],
  tags: ["lunchbox","conveyor","sorter","browser game","keyboard controls","touch controls","mobile-friendly","arcade puzzle","source-run"],
  artifactPath: "/artifacts/lunchbox-conveyor-sorter-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a226f21-260c-83ea-95fc-bdb3e43a3e3b",
  authorDisplayName: "Ari Morgan",
  authorUsername: "AriMorgan",
  createdAt: "2026-06-05T06:38:36Z",
  updatedAt: "2026-06-05T06:58:42.308Z",
  prompts: [
    "I keep picturing a lunchbox conveyor game where sandwiches, fruit, drinks, and treats roll past and I have to sort them into the right lunchboxes before recess. Could you turn that into a little browser game I can save as one HTML file and play right away?",
    "The first version is fun with dragging, but I need it to be playable without a mouse too. Add keyboard controls where number keys choose the next food item and arrow keys move the selected item between the conveyor and lunchboxes, while keeping touch dragging working.",
    "The controls are there now, but it still feels like endless arcade sorting. Add three short lunch-rush levels with clear goals: pack 8 items, then 12 with a faster belt, then a no-mistakes mixed round. Show the current goal and advance levels automatically so there is a reason to replay.",
    "The level goals help. One thing I would notice while playing with the keyboard is that the blue outlines are easy to miss. Add a small status strip that names the selected food and target lunchbox, plus quick Correct, Wrong, and Missed feedback so the player understands what just happened.",
    "This is close enough for the final version, but please do one mobile hardening pass: at about 390px wide there should be no page-level horizontal overflow, the overlay/card and four lunchboxes should fit cleanly, the belt label should not force the page wider, and touch dragging should not scroll the page. Keep the keyboard controls intact.",
    "I tested the final file and noticed it now pulls a Google Fonts URL. This needs to stay fully self-contained/offline. Remove any external font or resource URLs, keep the mobile no-overflow fixes, and leave the keyboard/touch controls working."
  ],
})

export const PORCH_PLANT_WATERING_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: PORCH_PLANT_WATERING_PROJECT_ID,
  sourceRunId: "ddbb720e-06dd-49b1-a870-da322efeaec8",
  href: "/porch-plant-watering-planner-demo",
  title: "Porch Plant Watering Planner",
  description: "A phone-first porch plant planner for adding plants by zone, tracking watering cadence, seeing today/overdue status, walking a zone route checklist, and backing up the plant list locally.",
  content: "Ivy Mason used Claude to build Porch Plant Watering Planner through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "A production-servable offline HTML porch watering planner under public/artifacts with add/edit plants, custom porch zones, cadence status, today/overdue view, route checklist, local persistence, and JSON backup/import controls.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Sonnet 4.6 Max (visible Claude composer model label)",
  modelRecommendation: "Sonnet 4.6 Max (visible Claude composer model label)",
  toolsUsed: ["Claude web UI","Chrome","local 390x844 iframe verification harness"],
  tags: ["porch plants","watering planner","home productivity","visual checklist","local storage","offline html","mobile-first","export import","source-run"],
  artifactPath: "/artifacts/porch-plant-watering-planner-claude.html",
  sourceUrl: "https://claude.ai/chat/2092273b-f3b5-4883-89ad-36f0dcd6f203",
  authorDisplayName: "Ivy Mason",
  authorUsername: "IvyMason",
  createdAt: "2026-06-05T06:39:00Z",
  updatedAt: "2026-06-05T07:01:30Z",
  prompts: [
    "My porch plants are where I always lose the plot; can you make me a little HTML planner I can save, with porch zones, watering cadence, what is due today or overdue, and a quick way to check watering off from my phone?",
    "This is already useful, but I noticed the file is pulling Google Fonts, and I want it to work even if my porch Wi-Fi is spotty. Remove any external resources and add a simple export/import backup for the plant list so I can move it between phones or recover it later.",
    "One more thing I'd actually use: summer weather changes the rhythm. Add a small Today conditions control for normal, hot/dry, and rainy, where hot/dry can pull borderline plants into today's list and rainy lets me mark a rain-soaked skip, with the reason shown on each card. No weather API.",
    "The Today list is good, but when I'm actually outside I move zone by zone. Add a compact visual route checklist at the top that groups today's due, overdue, or hot-pulled plants by porch zone, shows progress like 2 of 5 done, and updates as I water or log rain. Please keep the 390px phone layout tight.",
    "Last thing before I would actually rely on it: let me edit an existing plant's zone, cadence, last-watered date, and notes without deleting it, and do a final small-screen cleanup for wet-finger use at 390px wide. Keep the file offline-only and don't add anything network-based."
  ],
})

export const SHARED_ERRAND_ROUTE_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: SHARED_ERRAND_ROUTE_PROJECT_ID,
  sourceRunId: "c0349c7f-2df9-4c9d-a0e3-5d72af3becee",
  href: "/shared-errand-route-board-demo",
  title: "Shared Errand Route Board",
  description: "A self-contained household errand route board for adding, editing, assigning, categorizing, prioritizing, copying, exporting, and locally saving shared stops.",
  content: "Noah Hayes used Gemini to build Shared Errand Route Board through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "One-file HTML shared errand route planning board with editable stops, assignments/categories, filters, drag priority ordering, copied/exported handoff, mobile summary, and local persistence.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Gemini Flash (visible mode picker label: Flash; exact Gemini backend version not exposed in source UI)",
  modelRecommendation: "Gemini Flash (visible mode picker label: Flash; exact Gemini backend version not exposed in source UI)",
  toolsUsed: ["Gemini web UI","Chrome","headless Chrome local 390px verifier"],
  tags: ["errands","roommates","family planning","route board","shared household","one-file html","local storage","export","source-run"],
  artifactPath: "/artifacts/shared-errand-route-board-gemini.html",
  sourceUrl: "https://gemini.google.com/app/d3cf16be34b5de96",
  authorDisplayName: "Noah Hayes",
  authorUsername: "NoahHayes",
  createdAt: "2026-06-05T06:45:47.339Z",
  updatedAt: "2026-06-05T06:45:47.339Z",
  prompts: [
    "My roommates keep duplicating errands; can you create a self-contained HTML board where we can list stops, assign who is handling each one, drag priorities around, and copy a clean route plan?",
    "This is a good start, but people will need to change a stop after they add it. Add inline editing for the stop, assignee, and notes, and keep the drag ordering and copy route plan working.",
    "This is closer. I also want it to work when a family has stops that are grouped more by category than by person, so add a simple category field plus filters for assignee or category without making the form feel huge.",
    "The filters help, but on a phone I would want the route summary visible before the full list. Add a compact top summary with next stop, owner, unassigned count, and total stops, and make sure the layout is designed for a 390px-wide phone without page-level horizontal scrolling.",
    "One more thing I forgot: make the handoff useful outside the page. Add a download/export button and make the copied summary include route order plus grouped-by-assignee/category checkboxes, while preserving local saving and the 390px phone layout."
  ],
})

export const MINI_GOLF_WINDMILL_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: MINI_GOLF_WINDMILL_PROJECT_ID,
  sourceRunId: "1e93886f-37fa-4fef-a331-6ec3f9598a33",
  href: "/mini-golf-windmill-putt-demo",
  title: "Mini Golf Windmill Putt",
  description: "A one-screen browser mini golf game where the player aims one putt around a windmill blade, shapes the shot around a static bumper, and tries to finish under par.",
  content: "Priya Nair used ChatGPT to build Mini Golf Windmill Putt through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "One-file HTML canvas mini golf game with drag aiming, power meter, static bumper, moving windmill blade, stroke/par HUD, blade-hit feedback, and scorecard overlay.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "ChatGPT Instant visible composer setting; exact underlying model not exposed",
  modelRecommendation: "ChatGPT Instant visible composer setting; exact underlying model not exposed",
  toolsUsed: ["ChatGPT web normal lane","Chrome browser verification","headless Chrome CDP mobile verification"],
  tags: ["mini golf","windmill","browser game","one-screen game","mobile-friendly","canvas","source-run"],
  artifactPath: "/artifacts/mini-golf-windmill-putt-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a22616f-a0f0-83ea-9e19-47e0b7459794",
  authorDisplayName: "Priya Nair",
  authorUsername: "PriyaNair",
  createdAt: "2026-06-05T05:34:00Z",
  updatedAt: "2026-06-05T05:59:43Z",
  prompts: [
    "I want a tiny mini golf game where you line up one putt around a spinning windmill blade and try to finish under par. Can you make it as a single HTML file I can open and play right away?",
    "This runs, but it loads Google Fonts and I need the game to work fully offline. Please remove any external resources and tighten the HUD/aiming instructions for phone screens while keeping it one HTML file.",
    "I tried a putt and hit the blade; the game works, but the feedback is a little subtle. Add a clear aim line and power meter while dragging, and make blade hits feel obvious without adding any external assets.",
    "The putt and blade feedback are better now, but the “finish under par” goal still feels buried in the HUD. Add a small end-of-hole scorecard overlay when the ball drops, with birdie/par/bogey wording and an easy play-again action.",
    "The scorecard helps. The course still reads like a straight hallway through the windmill, though; add a small static contour or bumper so aiming around the windmill feels intentional, while keeping the windmill as the only moving obstacle.",
    "This is close. Please do one final mobile pass: no page-level horizontal overflow around 390px wide, the canvas and scorecard should scale cleanly, and touch/pointer aiming should not make the page scroll while you drag."
  ],
})

export const LEFTOVER_DINNER_BOARD_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: LEFTOVER_DINNER_BOARD_PROJECT_ID,
  sourceRunId: "a59e5346-930d-4592-9996-3a23970f7c22",
  href: "/leftover-dinner-decision-board-demo",
  title: "Leftover Dinner Decision Board",
  description: "One-file dinner planning board that turns leftovers and staples into ranked dinner options, prioritizing perishables and exporting a short plan.",
  content: "Theo Carter used Gemini to build Leftover Dinner Decision Board through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "A production-servable single-file HTML dinner decision board under public/artifacts that ranks dinner options by perishable usage and exports a short plan.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Gemini Flash (visible mode picker label: Flash; exact Gemini version not exposed in source UI)",
  modelRecommendation: "Gemini Flash (visible mode picker label: Flash; exact Gemini version not exposed in source UI)",
  toolsUsed: ["Gemini web UI","Chrome","local headless browser verification"],
  tags: ["leftovers","dinner planner","home productivity","meal planning","one-file html","local storage","printable export","source-run"],
  artifactPath: "/artifacts/leftover-dinner-board-gemini.html",
  sourceUrl: "https://gemini.google.com/app/c11e8cf1773a7965",
  authorDisplayName: "Theo Carter",
  authorUsername: "TheoCarter",
  createdAt: "2026-06-05T05:46:10.193Z",
  updatedAt: "2026-06-05T05:46:10.193Z",
  prompts: [
    "My fridge is in that awkward leftover zone; can you make me a single-file HTML dinner decision board where I can list leftovers and staples, mark what is most perishable, and get a few dinner ideas ranked by what uses up the risky stuff first, with a short plan I can print or export?",
    "This is useful, but I don't want to brainstorm every possible dinner manually each time. Add an automatic suggestion mode that looks at the listed leftovers/staples and proposes a few dinner options from simple patterns, while still letting me add a custom idea if I want.",
    "This is closer. I would use it over a few fridge clean-out nights, so add local save/restore for the inventory and both generated and custom meal ideas, plus a clear-board button. Keep the printed plan clean and focused on the ranked dinner choices.",
    "The ranked list is useful, but real leftovers are not just safe/risky. Add a quick quantity field and a days-left or urgency setting for each ingredient, then show a plain-English score reason on each dinner option so I can see why it ranked higher. Keep data entry fast.",
    "One last pass: make Export create a downloadable .txt dinner plan in addition to copying it, tighten the layout so it has no page-level horizontal overflow on a narrow phone around 390px wide, and make the main button labels obvious for someone using this while standing in the kitchen. Please keep it all in one HTML file with no external assets."
  ],
})

export const TINY_LOOP_SEQUENCER_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: TINY_LOOP_SEQUENCER_PROJECT_ID,
  sourceRunId: "8b68c6c9-451a-4c72-b7bc-262a64233292",
  href: "/tiny-loop-sequencer-demo",
  title: "Tiny Loop Sequencer",
  description: "Tiny Loop Sequencer was captured as a PathForge source run and prepared as an artifact-first public page.",
  content: "Owen Brooks used OpenRouter to build Tiny Loop Sequencer through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "A self-contained Tiny Loop Sequencer artifact embedded directly on the page with the captured prompt and response packages preserved below it.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "Anthropic Claude Haiku Latest (~anthropic/claude-haiku-latest); visible upstream response model: Claude Haiku 4.5",
  modelRecommendation: "Anthropic Claude Haiku Latest (~anthropic/claude-haiku-latest); visible upstream response model: Claude Haiku 4.5",
  toolsUsed: ["OpenRouter","HTML","Browser"],
  tags: ["web-audio","music","sequencer","creative-toy","single-file-html","local-storage","source-run"],
  artifactPath: "/artifacts/tiny-loop-sequencer-claude-step-5.html",
  sourceUrl: "https://openrouter.ai/chat?room=orc-1780634365-MCz7i1oIfBu94tWR8LDt",
  authorDisplayName: "Owen Brooks",
  authorUsername: "OwenBrooks",
  createdAt: "2026-06-05T04:47:43.701Z",
  updatedAt: "2026-06-05T04:47:43.701Z",
  prompts: [
    "I'm making a little late-night beat sketcher for non-musicians: give me one self-contained HTML file with a 16-step grid, a few Web Audio sounds, and a start/stop button that stays silent until I press play.",
    "The first version is close, but the scheduler can reach step 16 before wrapping and the playhead display is a little jumpy. Fix the wraparound/playhead timing and give me the full updated HTML again.",
    "Now that the timing is cleaner, the grid is still hard to read at a glance. Add numbered beat columns, stronger downbeat accents, and a tiny clear/random button per instrument row, then send the full updated HTML.",
    "This is getting usable, but on a phone those grouped steps will probably be tiny. Redesign the controls for touch: keep all 16 steps reachable, avoid horizontal page overflow, and send the full updated HTML.",
    "I forgot that people will want to come back to a pattern. Add localStorage save/load/clear for the grid and tempo, keep it silent until Play, and send the full updated HTML."
  ],
})

export const GARAGE_SALE_TAGS_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: GARAGE_SALE_TAGS_PROJECT_ID,
  sourceRunId: "20dd647b-960f-4c7e-a0de-6bc673954b41",
  href: "/garage-sale-price-tag-maker-demo",
  title: "Garage Sale Price Tag Maker",
  description: "Garage Sale Price Tag Maker was captured as a PathForge source run and prepared as an artifact-first public page.",
  content: "Mina Park used Gemini to build Garage Sale Price Tag Maker through a 6-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "A self-contained Garage Sale Price Tag Maker artifact embedded directly on the page with the captured prompt and response packages preserved below it.",
  categorySlug: "productivity",
  mockCategoryId: "cat-7",
  difficulty: 'beginner',
  modelUsed: "Gemini 3.5 Flash",
  modelRecommendation: "Gemini 3.5 Flash",
  toolsUsed: ["Gemini","HTML","Browser"],
  tags: ["garage sale","price tags","printing","inventory","export","local storage","source-run"],
  artifactPath: "/artifacts/garage-sale-tags-gemini.html",
  sourceUrl: "https://gemini.google.com/app/12086e073ef8b1ac",
  authorDisplayName: "Mina Park",
  authorUsername: "MinaPark",
  createdAt: "2026-06-05T04:20:00.000Z",
  updatedAt: "2026-06-05T05:21:40.198Z",
  prompts: [
    "I'm doing a neighborhood garage sale this weekend and need a tiny browser tool where I can enter items and prices, print clean price tags, and keep a simple total sheet. Can you make it as one HTML file I can save and use offline?",
    "This is a good start, but if I mistype a price I need to edit or delete the item before printing. Add simple inline edit/delete controls and keep the printed pages clean.",
    "I realized I'd probably build the list over a few nights, so add local browser saving plus a Clear All button with confirmation. Please resend the full compact HTML file and keep those controls out of print.",
    "This is useful; for pricing day I also want a quick copy/export summary so I can paste the item list into a text message or spreadsheet. Add a copy summary button and CSV download, while leaving the print layout clean.",
    "One last thing: during the sale I want to mark items sold and see actual cash collected separately from the total priced inventory. Add sold checkboxes/status with sold total and remaining value, without making the tags messy.",
    "I tested the final file on a narrow phone viewport: at 390px wide it still horizontally scrolls, with clientWidth 390 and scrollWidth about 563. Please resend the full HTML with the mobile overflow fixed, while preserving the print layout, copy summary, CSV export, sold checkboxes, local saving, and clean price tags."
  ],
})

export const MICRO_DUNGEON_ROUTE_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: MICRO_DUNGEON_ROUTE_PROJECT_ID,
  sourceRunId: "eec3048a-6cb2-4b57-948f-78cc0f65ae83",
  href: "/micro-dungeon-route-puzzle-demo",
  title: "Micro Dungeon Route Puzzle",
  description: "A self-contained browser route-planning puzzle where players sketch a path through keys, traps, locked doors, and exits, then run and score the plan.",
  content: "Jules Morgan used ChatGPT to build Micro Dungeon Route Puzzle through a 7-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Self-contained HTML dungeon route puzzle with plan-then-run gameplay, handcrafted levels, keys/doors/traps/collapsing floors, par scoring, saved best scores, hints, keyboard controls, and mobile-responsive layout.",
  categorySlug: "personal",
  mockCategoryId: "cat-10",
  difficulty: 'beginner',
  modelUsed: "Latest 5.5 / gpt-5-5-thinking as exposed by ChatGPT message nodes",
  modelRecommendation: "Latest 5.5 / gpt-5-5-thinking as exposed by ChatGPT message nodes",
  toolsUsed: ["ChatGPT web in Chrome","local static server","Chrome browser verification"],
  tags: ["browser-game","puzzle","route-planning","dungeon","single-file-html","keyboard-controls","local-storage","source-run"],
  artifactPath: "/artifacts/micro-dungeon-route-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a2252a3-639c-83ea-9b62-94cbdaa665af",
  authorDisplayName: "Jules Morgan",
  authorUsername: "JulesMorgan",
  createdAt: "2026-06-05T04:44:40.869Z",
  updatedAt: "2026-06-05T05:11:37.468Z",
  prompts: [
    "I want a small dungeon-route puzzle I can play in the browser: a grid of rooms where I have to pick a route through keys, traps, locked doors, and an exit. Could you build it as one self-contained HTML file and make the puzzle feel clear enough to solve without instructions outside the page?",
    "This works, but it feels more like clicking one move at a time than planning a route. Add a planning mode where I can sketch the whole path first, then press Run Route to animate and validate it; keep it as one self-contained HTML file.",
    "The planner works now. Add par targets and route quality: show the target steps for each level, label a solved run as perfect, clean, or too long, and save the best step count per level in local storage. Keep the planner simple and one-file.",
    "I like the scoring, but failed plans should teach me what went wrong. Add a failed-run breakdown that highlights the exact step that breaks the route—missing key, trap death, collapsed floor, wall, or dead end—and include one optional hint for the current level without auto-solving it.",
    "This is close. Do one final polish pass so it feels ready to host: make the grid and side panel work cleanly on phones, add keyboard planning with arrow keys plus Enter to run and Backspace to undo, and keep the file self-contained with no external assets or backend.",
    "I found one bug in that version: after solving a level, Reset does not fully clear the solved route before I start a new keyboard plan, so Backspace removes from the old solved path instead of a fresh plan. Fix Reset, Clear Plan, and level changes so they always return to a clean planning state while keeping the keyboard controls, hints, scoring, and mobile polish.",
    "The reset bug is still there in my local test: after a solved 9-step route, pressing Reset leaves PLANNED at 9 and says the planned route is still on the board; Backspace then drops that old route to 8. Please fix the actual state mutation so Reset returns the board to only Start with PLANNED 0, Clear Plan does the same without changing the level, and after one ArrowRight then Backspace it returns to PLANNED 0. Keep all other features and return the full self-contained HTML."
  ],
})

export const BAKE_SALE_MARGIN_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: BAKE_SALE_MARGIN_PROJECT_ID,
  sourceRunId: "8a2e82c9-4ae1-41bc-b74a-0a77f70516c6",
  href: "/pocket-bake-sale-margin-calculator-demo",
  title: "Pocket Bake-Sale Margin Calculator",
  description: "A seven-prompt Gemini source run produced an offline one-file bake-sale planning tool for entering ingredient/package costs, batch yield, packaging, target price, table goal, and printable/exportable sales summaries.",
  content: "Clara Bennett used Gemini to build Pocket Bake-Sale Margin Calculator through a 7-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Self-contained bake-sale recipe cost and margin planner with ingredient cost rows, batch yield, packaging, target price, break-even units, printable summary, browser save/restore including ingredient rows, copy summary, and text export/download.",
  categorySlug: "finance",
  mockCategoryId: "cat-1",
  difficulty: 'beginner',
  modelUsed: "Gemini 3.1 Flash-Lite",
  modelRecommendation: "Gemini 3.1 Flash-Lite",
  toolsUsed: ["Gemini","Chrome","HTML","local browser verification"],
  tags: ["bake sale","recipe costing","margin calculator","small business","food planning","printable labels","local storage","single-file html","Gemini Flash-Lite","source-run"],
  artifactPath: "/artifacts/bake-sale-margin-gemini-step-7.html",
  sourceUrl: "https://gemini.google.com/app/37e608f88e32bdbf",
  authorDisplayName: "Clara Bennett",
  authorUsername: "ClaraBennett",
  createdAt: "2026-06-05T03:24:00Z",
  updatedAt: "2026-06-05T03:46:23.849Z",
  prompts: [
    "I'm planning a tiny bake-sale table and I need a calculator I can save as one HTML file to check ingredient costs, batch yield, packaging, and whether my cookie price leaves a real margin.",
    "This is a decent start, but I need to enter the ingredients one by one so I can see what is actually driving the cost. Please revise it with ingredient rows, quantities, package prices, and the complete updated HTML so I don't have to stitch pieces together.",
    "This is closer. For the bake-sale table, the main thing I need to decide is whether a price is worth it, so add total batch cost, cost per item including packaging, a target-margin price suggestion, and how many items I need to sell to break even on a table goal. Also, please return the updated file as direct HTML this time, not a Python wrapper.",
    "Good, but I still need to test the actual sticker price I plan to put on the table, not just the suggested price. Add a target price input, show profit and margin at that price with a clear red/yellow/green cue, and make the break-even section use the chosen target price too.",
    "The calculator part is useful now. For actually running the table, add a product name, items-per-pack field, a printable price label area, and a copyable/printable summary that includes cost per item, target price, margin, break-even units, and batch profit. Keep it offline in the same HTML file.",
    "Before I call this done, add the practical bits I would miss during setup: save the current recipe in the browser, add a copy-summary button that puts plain text on the clipboard, add a simple download/export for the summary, and tighten the mobile layout so the ingredient table does not spill off the screen.",
    "I tested the save behavior: the product, yield, and price fields come back after reload, but the ingredient rows do not. Please fix save/load so ingredient names, package prices, package sizes, amounts used, and added rows all restore after reload, while keeping the copy, export, print, and mobile layout work."
  ],
})

export const STAR_MAP_SCAVENGER_SHOWCASE_PROJECT = buildPendingSourceRunProject({
  projectId: STAR_MAP_SCAVENGER_PROJECT_ID,
  sourceRunId: "7a94908b-cb26-4e8e-9b52-eec662066864",
  href: "/backyard-star-map-scavenger-hunt-builder-demo",
  title: "Backyard Star-Map Scavenger Hunt Builder",
  description: "A five-prompt ChatGPT source run produced an offline single-file HTML family activity tool for building a printable backyard stargazing scavenger hunt with date/sky notes, compass sky-map zones, clue cards, a finder checklist, parent answer key, adult setup checklist, sample-night fill, copyable text export, local persistence, and print controls.",
  content: "Harper Wells used ChatGPT to build Backyard Star-Map Scavenger Hunt Builder through a 5-prompt source run. The public page keeps the final artifact first, then preserves each exact prompt and response package in order with selectable artifact versions when the run produced them.",
  resultContent: "Offline printable backyard stargazing scavenger-hunt builder with clue-card selection, compass sky-map search zones, separate kid and parent print packs, answer key, adult setup checklist, copy/export text, sample-night fill, reset, custom target support, and local persistence.",
  categorySlug: "education",
  mockCategoryId: "cat-6",
  difficulty: 'beginner',
  modelUsed: "Latest 5.5 / gpt-5-5-thinking as exposed by ChatGPT message nodes",
  modelRecommendation: "Latest 5.5 / gpt-5-5-thinking as exposed by ChatGPT message nodes",
  toolsUsed: ["ChatGPT","Chrome","local static HTTP server","Codex package verification"],
  tags: ["stargazing","family-activity","scavenger-hunt","printable","sky-map","checklist","clue-cards","offline-html","ChatGPT","source-run"],
  artifactPath: "/artifacts/star-map-scavenger-chatgpt.html",
  sourceUrl: "https://chatgpt.com/c/6a22442b-a8a8-83ea-816c-762c017243ae",
  authorDisplayName: "Harper Wells",
  authorUsername: "HarperWells",
  createdAt: "2026-06-05T03:08:00Z",
  updatedAt: "2026-06-05T03:51:06Z",
  prompts: [
    "I’m putting together a backyard stargazing scavenger hunt for kids tonight. Could you build me a self-contained HTML page where I can enter the date, a rough location/sky note, and then print clue cards plus a checklist for things to find?",
    "This is a good start. Two things I’d need before using it with kids: keep a parent answer key separate from the clue cards, and add a copy/export text version I can send to another parent. Please return the full updated HTML so I can replace the file.",
    "The parent/export pieces help. The tool still feels more like a clue list than a star-map hunt, though. Add a simple printable sky-map panel with north/east/south/west zones and let each clue suggest where to look, without pretending to calculate exact positions. Return the full updated HTML.",
    "This is close. I’d also want a one-click sample backyard night so I can see the whole flow filled in fast, plus a small adult setup checklist for things like flashlights, blankets, boundaries, and what to do if clouds roll in. Keep it offline and return the complete updated HTML.",
    "I tried to imagine using this on a phone by the back door, and the controls/card library could get tall. Tighten the small-screen layout: make the action buttons easier to hit, reduce horizontal crowding in the clue list, and make sure the print pages still stay clean. Return the complete updated HTML."
  ],
})

export const PENDING_SOURCE_RUN_SHOWCASE_PROJECTS = [
  TINY_TRAIN_DISPATCHER_SHOWCASE_PROJECT,
  BREAKROOM_SNACK_RESTOCK_SHOWCASE_PROJECT,
  PORCH_LIGHT_MOTH_MAZE_SHOWCASE_PROJECT,
  PANTRY_SHELF_LIFE_RESCUE_SHOWCASE_PROJECT,
  MINI_HARBOR_TUGBOAT_SHOWCASE_PROJECT,
  TINY_FARMERS_MARKET_SHOWCASE_PROJECT,
  ROOMMATE_CHORE_DRAFT_SHOWCASE_PROJECT,
  POCKET_PIRATE_MAP_SHOWCASE_PROJECT,
  POTLUCK_TABLE_PLANNER_SHOWCASE_PROJECT,
  RAINY_WINDOW_CAFE_RUSH_SHOWCASE_PROJECT,
  LUNCHBOX_CONVEYOR_SORTER_SHOWCASE_PROJECT,
  PORCH_PLANT_WATERING_SHOWCASE_PROJECT,
  SHARED_ERRAND_ROUTE_SHOWCASE_PROJECT,
  MINI_GOLF_WINDMILL_SHOWCASE_PROJECT,
  LEFTOVER_DINNER_BOARD_SHOWCASE_PROJECT,
  TINY_LOOP_SEQUENCER_SHOWCASE_PROJECT,
  GARAGE_SALE_TAGS_SHOWCASE_PROJECT,
  MICRO_DUNGEON_ROUTE_SHOWCASE_PROJECT,
  BAKE_SALE_MARGIN_SHOWCASE_PROJECT,
  STAR_MAP_SCAVENGER_SHOWCASE_PROJECT,
]
