import type { Prompt, PromptWithRelations } from './types'
import {
  AIRLOCK_ZERO_CLAUDE_FORK_PROJECT_ID,
  AIRLOCK_ZERO_GEMINI_FORK_PROJECT_ID,
  AIRLOCK_ZERO_GPT_FORK_PROJECT_ID,
  AIRLOCK_ZERO_PROJECT_ID,
  TINY_TRAIN_DISPATCHER_PROJECT_ID,
  BREAKROOM_SNACK_RESTOCK_PROJECT_ID,
  PORCH_LIGHT_MOTH_MAZE_PROJECT_ID,
  PANTRY_SHELF_LIFE_RESCUE_PROJECT_ID,
  MINI_HARBOR_TUGBOAT_PROJECT_ID,
  TINY_FARMERS_MARKET_PROJECT_ID,
  ROOMMATE_CHORE_DRAFT_PROJECT_ID,
  POCKET_PIRATE_MAP_PROJECT_ID,
  POTLUCK_TABLE_PLANNER_PROJECT_ID,
  RAINY_WINDOW_CAFE_RUSH_PROJECT_ID,
  LUNCHBOX_CONVEYOR_SORTER_PROJECT_ID,
  PORCH_PLANT_WATERING_PROJECT_ID,
  SHARED_ERRAND_ROUTE_PROJECT_ID,
  MINI_GOLF_WINDMILL_PROJECT_ID,
  LEFTOVER_DINNER_BOARD_PROJECT_ID,
  TINY_LOOP_SEQUENCER_PROJECT_ID,
  GARAGE_SALE_TAGS_PROJECT_ID,
  MICRO_DUNGEON_ROUTE_PROJECT_ID,
  BAKE_SALE_MARGIN_PROJECT_ID,
  STAR_MAP_SCAVENGER_PROJECT_ID,
  DECISION_MATRIX_PROJECT_ID,
  FLASHCARD_CRAM_PROJECT_ID,
  FOLLOW_UP_CRM_PROJECT_ID,
  HP_10BII_PROJECT_ID,
  LANE_DEFENSE_PROJECT_ID,
  MEETING_COST_PROJECT_ID,
  NEON_BLOCK_PATROL_PROJECT_ID,
  POCKET_RALLY_PROJECT_ID,
  POMODORO_TIMER_PROJECT_ID,
  PUZZLE_BOX_ESCAPE_PROJECT_ID,
  REACTION_TRAINER_PROJECT_ID,
  SCHOOL_DESK_HP_CALCULATOR_FORK_PROJECT_ID,
  SNAKE_PROJECT_ID,
  SNAKE_PROJECT_LEGACY_ID,
  SWISH_CITY_PROJECT_ID,
  TIC_TAC_TOE_PROJECT_ID,
  TRIP_PACKING_PROJECT_ID,
  WEEKEND_CHECKLIST_REAL_FORK_PROJECT_ID,
  WEEKEND_CHECKLIST_PROJECT_ID,
  WORD_LADDER_SPRINT_PROJECT_ID,
  NEIGHBORHOOD_LOST_AND_FOUND_PROJECT_ID,
  TINY_DINER_TICKET_PROJECT_ID,
  SMALL_CLINIC_CALLBACK_PROJECT_ID,
  TINY_BIRTHDAY_RSVP_PROJECT_ID,
  TINY_AIRPORT_GATE_PROJECT_ID,
  TINY_FERRY_LOADING_PROJECT_ID,
  AFTER_SCHOOL_PICKUP_PROJECT_ID,
  FRIDGE_LEFTOVER_LABEL_PROJECT_ID,
  TINY_PARKING_LOT_PROJECT_ID,
  TINY_WINDOW_HERB_PROJECT_ID,
  POPUP_DINNER_SEATING_PROJECT_ID,
  TINY_CROSSWALK_TIMING_PROJECT_ID,
  TINY_INVOICE_NUDGE_PROJECT_ID,
  MAILROOM_CART_ROUTE_PROJECT_ID,
  NEIGHBORHOOD_POTLUCK_BALANCER_PROJECT_ID,
  LAUNDROMAT_SOCK_SORTER_PROJECT_ID,
  CORNER_STORE_CHANGE_PROJECT_ID,
  WEEKEND_YARD_SALE_PROJECT_ID,
  MINI_METRO_SIGNAL_PROJECT_ID,
  MOVING_DAY_BOX_LABELER_PROJECT_ID,
  ROOFTOP_COURIER_SWITCHBACKS_PROJECT_ID,
  NEIGHBORHOOD_SNOW_ROUTE_PROJECT_ID,
  ROOMMATE_FREEZER_BOARD_PROJECT_ID,
  UTILITY_BILL_BALANCE_PROJECT_ID,
  BLOCK_BIKE_COURIER_PROJECT_ID,
} from './featured-projects'
import { RECOVERED_SOURCE_RUN_ROUTE_OVERRIDES } from './recovered-source-run-showcases'

const PROJECT_ROUTE_OVERRIDES: Record<string, string> = {
  ...RECOVERED_SOURCE_RUN_ROUTE_OVERRIDES,
  [AIRLOCK_ZERO_PROJECT_ID]: '/airlock-zero-reactor-run-demo',
  [AIRLOCK_ZERO_CLAUDE_FORK_PROJECT_ID]: '/airlock-zero-blackout-shift-fork-demo',
  [AIRLOCK_ZERO_GPT_FORK_PROJECT_ID]: '/airlock-zero-swarm-shift-fork-demo',
  [AIRLOCK_ZERO_GEMINI_FORK_PROJECT_ID]: '/airlock-zero-hull-breach-fork-demo',
  'dc5e67c3-42d0-4823-ae23-586b7d3985cb': '/calming-sleep-sound-mixer-demo',
  '0ddfc7cf-37bf-47ae-8fe0-d8d445ba1bee': '/booking-flow-handoff-simulator-demo',
  'e0e4e2b7-082e-4db1-9468-484fc3fd3a69': '/first-principles-claim-ladder-game-demo',
  'ca0c2e08-9e02-4725-90f5-58ef248fe4c7': '/gym-mirror-progress-shot-consistency-studio-demo',
  '22bcc36b-497f-43f7-824f-3ccba9690da6': '/rental-walkthrough-red-flag-scorecard-demo',
  '384ebd4d-88af-400b-b230-4eb771bb2194': '/security-cam-anomaly-timeline-game-demo',
  '17c42c87-3709-4d5e-9ae3-d4ac4807bc4c': '/t-shirt-print-alignment-press-game-demo',
  'a7201847-c8d6-4e09-814b-0a382f8f8080': '/tiny-festival-set-time-clash-game-demo',
  [TINY_TRAIN_DISPATCHER_PROJECT_ID]: '/tiny-train-platform-dispatcher-demo',
  [BREAKROOM_SNACK_RESTOCK_PROJECT_ID]: '/breakroom-snack-restock-planner-demo',
  [PORCH_LIGHT_MOTH_MAZE_PROJECT_ID]: '/porch-light-moth-maze-demo',
  [PANTRY_SHELF_LIFE_RESCUE_PROJECT_ID]: '/pantry-shelf-life-rescue-planner-demo',
  [MINI_HARBOR_TUGBOAT_PROJECT_ID]: '/mini-harbor-tugboat-switcher-demo',
  [TINY_FARMERS_MARKET_PROJECT_ID]: '/tiny-farmers-market-booth-simulator-demo',
  [ROOMMATE_CHORE_DRAFT_PROJECT_ID]: '/roommate-chore-draft-board-demo',
  [POCKET_PIRATE_MAP_PROJECT_ID]: '/pocket-pirate-map-decoder-demo',
  [POTLUCK_TABLE_PLANNER_PROJECT_ID]: '/potluck-table-planner-demo',
  [RAINY_WINDOW_CAFE_RUSH_PROJECT_ID]: '/rainy-window-cafe-rush-demo',
  [LUNCHBOX_CONVEYOR_SORTER_PROJECT_ID]: '/lunchbox-conveyor-sorter-demo',
  [PORCH_PLANT_WATERING_PROJECT_ID]: '/porch-plant-watering-planner-demo',
  [SHARED_ERRAND_ROUTE_PROJECT_ID]: '/shared-errand-route-board-demo',
  [MINI_GOLF_WINDMILL_PROJECT_ID]: '/mini-golf-windmill-putt-demo',
  [LEFTOVER_DINNER_BOARD_PROJECT_ID]: '/leftover-dinner-decision-board-demo',
  [TINY_LOOP_SEQUENCER_PROJECT_ID]: '/tiny-loop-sequencer-demo',
  [GARAGE_SALE_TAGS_PROJECT_ID]: '/garage-sale-price-tag-maker-demo',
  [MICRO_DUNGEON_ROUTE_PROJECT_ID]: '/micro-dungeon-route-puzzle-demo',
  [BAKE_SALE_MARGIN_PROJECT_ID]: '/pocket-bake-sale-margin-calculator-demo',
  [STAR_MAP_SCAVENGER_PROJECT_ID]: '/backyard-star-map-scavenger-hunt-builder-demo',
  [NEIGHBORHOOD_LOST_AND_FOUND_PROJECT_ID]: '/neighborhood-lost-and-found-claim-board-demo',
  [TINY_DINER_TICKET_PROJECT_ID]: '/tiny-diner-ticket-time-trial-demo',
  [SMALL_CLINIC_CALLBACK_PROJECT_ID]: '/small-clinic-callback-queue-board-demo',
  [TINY_BIRTHDAY_RSVP_PROJECT_ID]: '/tiny-birthday-rsvp-table-planner-demo',
  [TINY_AIRPORT_GATE_PROJECT_ID]: '/tiny-airport-gate-boarding-sorter-demo',
  [TINY_FERRY_LOADING_PROJECT_ID]: '/tiny-ferry-loading-puzzle-demo',
  [AFTER_SCHOOL_PICKUP_PROJECT_ID]: '/after-school-pickup-roster-demo',
  [FRIDGE_LEFTOVER_LABEL_PROJECT_ID]: '/fridge-leftover-label-printer-demo',
  [TINY_PARKING_LOT_PROJECT_ID]: '/tiny-parking-lot-cone-course-demo',
  [TINY_WINDOW_HERB_PROJECT_ID]: '/tiny-window-herb-light-planner-demo',
  [POPUP_DINNER_SEATING_PROJECT_ID]: '/pop-up-dinner-seating-mixer-demo',
  [TINY_CROSSWALK_TIMING_PROJECT_ID]: '/tiny-crosswalk-timing-trainer-demo',
  [TINY_INVOICE_NUDGE_PROJECT_ID]: '/tiny-invoice-nudge-board-demo',
  [MAILROOM_CART_ROUTE_PROJECT_ID]: '/mailroom-cart-route-puzzle-demo',
  [NEIGHBORHOOD_POTLUCK_BALANCER_PROJECT_ID]: '/neighborhood-potluck-balancer-demo',
  [LAUNDROMAT_SOCK_SORTER_PROJECT_ID]: '/laundromat-sock-sorter-demo',
  [CORNER_STORE_CHANGE_PROJECT_ID]: '/corner-store-change-rush-demo',
  [WEEKEND_YARD_SALE_PROJECT_ID]: '/weekend-yard-sale-table-mapper-demo',
  [MINI_METRO_SIGNAL_PROJECT_ID]: '/mini-metro-signal-desk-demo',
  [MOVING_DAY_BOX_LABELER_PROJECT_ID]: '/moving-day-box-labeler-demo',
  [ROOFTOP_COURIER_SWITCHBACKS_PROJECT_ID]: '/rooftop-courier-switchbacks-demo',
  [NEIGHBORHOOD_SNOW_ROUTE_PROJECT_ID]: '/neighborhood-snow-route-plow-puzzle-demo',
  [ROOMMATE_FREEZER_BOARD_PROJECT_ID]: '/roommate-freezer-board-demo',
  [UTILITY_BILL_BALANCE_PROJECT_ID]: '/utility-bill-balance-board-demo',
  [BLOCK_BIKE_COURIER_PROJECT_ID]: '/block-bike-courier-light-run-demo',
  [SNAKE_PROJECT_ID]: '/snake-demo',
  [SNAKE_PROJECT_LEGACY_ID]: '/snake-demo',
  [DECISION_MATRIX_PROJECT_ID]: '/decision-matrix-demo',
  [HP_10BII_PROJECT_ID]: '/hp-10bii-calculator-demo',
  [SCHOOL_DESK_HP_CALCULATOR_FORK_PROJECT_ID]: '/school-desk-hp-calculator-fork-demo',
  [TIC_TAC_TOE_PROJECT_ID]: '/tic-tac-toe-demo',
  [POMODORO_TIMER_PROJECT_ID]: '/pomodoro-timer-demo',
  [WEEKEND_CHECKLIST_PROJECT_ID]: '/weekend-plan-checklist-demo',
  [WEEKEND_CHECKLIST_REAL_FORK_PROJECT_ID]: '/weekend-family-road-trip-readiness-fork-demo',
  [NEON_BLOCK_PATROL_PROJECT_ID]: '/neon-block-patrol-demo',
  [SWISH_CITY_PROJECT_ID]: '/swish-city-timing-hoops-demo',
  [MEETING_COST_PROJECT_ID]: '/meeting-cost-calculator-demo',
  [WORD_LADDER_SPRINT_PROJECT_ID]: '/word-ladder-sprint-demo',
  [PUZZLE_BOX_ESCAPE_PROJECT_ID]: '/puzzle-box-escape-demo',
  [POCKET_RALLY_PROJECT_ID]: '/pocket-rally-time-trial-demo',
  [TRIP_PACKING_PROJECT_ID]: '/trip-packing-planner-demo',
  [FLASHCARD_CRAM_PROJECT_ID]: '/flashcard-cram-drill-demo',
  [FOLLOW_UP_CRM_PROJECT_ID]: '/follow-up-crm-tracker-demo',
  [REACTION_TRAINER_PROJECT_ID]: '/reaction-time-trainer-demo',
  [LANE_DEFENSE_PROJECT_ID]: '/tiny-lane-defense-demo',
}

export function getProjectRouteOverride(projectId: string) {
  return PROJECT_ROUTE_OVERRIDES[projectId] ?? null
}

export function getProjectRouteOverrideEntries() {
  return Object.entries(PROJECT_ROUTE_OVERRIDES)
}

export function getProjectHref(project: Pick<Prompt | PromptWithRelations, 'id'>) {
  return PROJECT_ROUTE_OVERRIDES[project.id] ?? `/prompt/${project.id}`
}
