import type { Prompt, PromptWithRelations } from './types'
import {
  TINY_TRAIN_DISPATCHER_PROJECT_ID,
  BREAKROOM_SNACK_RESTOCK_PROJECT_ID,
  PORCH_LIGHT_MOTH_MAZE_PROJECT_ID,
  PANTRY_SHELF_LIFE_RESCUE_PROJECT_ID,
  MINI_HARBOR_TUGBOAT_PROJECT_ID,
  TINY_FARMERS_MARKET_PROJECT_ID,
  ROOMMATE_CHORE_DRAFT_PROJECT_ID,
  POCKET_PIRATE_MAP_PROJECT_ID,
  POTLUCK_TABLE_PLANNER_PROJECT_ID,
  RAINY_WINDOW_CAFE_RUSH_PROJECT_ID,
  LUNCHBOX_CONVEYOR_SORTER_PROJECT_ID,
  PORCH_PLANT_WATERING_PROJECT_ID,
  SHARED_ERRAND_ROUTE_PROJECT_ID,
  MINI_GOLF_WINDMILL_PROJECT_ID,
  LEFTOVER_DINNER_BOARD_PROJECT_ID,
  TINY_LOOP_SEQUENCER_PROJECT_ID,
  GARAGE_SALE_TAGS_PROJECT_ID,
  MICRO_DUNGEON_ROUTE_PROJECT_ID,
  BAKE_SALE_MARGIN_PROJECT_ID,
  STAR_MAP_SCAVENGER_PROJECT_ID,
  DECISION_MATRIX_PROJECT_ID,
  FLASHCARD_CRAM_PROJECT_ID,
  FOLLOW_UP_CRM_PROJECT_ID,
  HP_10BII_PROJECT_ID,
  LANE_DEFENSE_PROJECT_ID,
  MEETING_COST_PROJECT_ID,
  NEON_BLOCK_PATROL_PROJECT_ID,
  POCKET_RALLY_PROJECT_ID,
  POMODORO_TIMER_PROJECT_ID,
  PUZZLE_BOX_ESCAPE_PROJECT_ID,
  REACTION_TRAINER_PROJECT_ID,
  SNAKE_PROJECT_ID,
  SNAKE_PROJECT_LEGACY_ID,
  SWISH_CITY_PROJECT_ID,
  TIC_TAC_TOE_PROJECT_ID,
  TRIP_PACKING_PROJECT_ID,
  WEEKEND_CHECKLIST_PROJECT_ID,
  WORD_LADDER_SPRINT_PROJECT_ID,
} from './featured-projects'

const PROJECT_ROUTE_OVERRIDES: Record<string, string> = {
  [TINY_TRAIN_DISPATCHER_PROJECT_ID]: '/tiny-train-platform-dispatcher-demo',
  [BREAKROOM_SNACK_RESTOCK_PROJECT_ID]: '/breakroom-snack-restock-planner-demo',
  [PORCH_LIGHT_MOTH_MAZE_PROJECT_ID]: '/porch-light-moth-maze-demo',
  [PANTRY_SHELF_LIFE_RESCUE_PROJECT_ID]: '/pantry-shelf-life-rescue-planner-demo',
  [MINI_HARBOR_TUGBOAT_PROJECT_ID]: '/mini-harbor-tugboat-switcher-demo',
  [TINY_FARMERS_MARKET_PROJECT_ID]: '/tiny-farmers-market-booth-simulator-demo',
  [ROOMMATE_CHORE_DRAFT_PROJECT_ID]: '/roommate-chore-draft-board-demo',
  [POCKET_PIRATE_MAP_PROJECT_ID]: '/pocket-pirate-map-decoder-demo',
  [POTLUCK_TABLE_PLANNER_PROJECT_ID]: '/potluck-table-planner-demo',
  [RAINY_WINDOW_CAFE_RUSH_PROJECT_ID]: '/rainy-window-cafe-rush-demo',
  [LUNCHBOX_CONVEYOR_SORTER_PROJECT_ID]: '/lunchbox-conveyor-sorter-demo',
  [PORCH_PLANT_WATERING_PROJECT_ID]: '/porch-plant-watering-planner-demo',
  [SHARED_ERRAND_ROUTE_PROJECT_ID]: '/shared-errand-route-board-demo',
  [MINI_GOLF_WINDMILL_PROJECT_ID]: '/mini-golf-windmill-putt-demo',
  [LEFTOVER_DINNER_BOARD_PROJECT_ID]: '/leftover-dinner-decision-board-demo',
  [TINY_LOOP_SEQUENCER_PROJECT_ID]: '/tiny-loop-sequencer-demo',
  [GARAGE_SALE_TAGS_PROJECT_ID]: '/garage-sale-price-tag-maker-demo',
  [MICRO_DUNGEON_ROUTE_PROJECT_ID]: '/micro-dungeon-route-puzzle-demo',
  [BAKE_SALE_MARGIN_PROJECT_ID]: '/pocket-bake-sale-margin-calculator-demo',
  [STAR_MAP_SCAVENGER_PROJECT_ID]: '/backyard-star-map-scavenger-hunt-builder-demo',
  [SNAKE_PROJECT_ID]: '/snake-demo',
  [SNAKE_PROJECT_LEGACY_ID]: '/snake-demo',
  [DECISION_MATRIX_PROJECT_ID]: '/decision-matrix-demo',
  [HP_10BII_PROJECT_ID]: '/hp-10bii-calculator-demo',
  [TIC_TAC_TOE_PROJECT_ID]: '/tic-tac-toe-demo',
  [POMODORO_TIMER_PROJECT_ID]: '/pomodoro-timer-demo',
  [WEEKEND_CHECKLIST_PROJECT_ID]: '/weekend-plan-checklist-demo',
  [NEON_BLOCK_PATROL_PROJECT_ID]: '/neon-block-patrol-demo',
  [SWISH_CITY_PROJECT_ID]: '/swish-city-timing-hoops-demo',
  [MEETING_COST_PROJECT_ID]: '/meeting-cost-calculator-demo',
  [WORD_LADDER_SPRINT_PROJECT_ID]: '/word-ladder-sprint-demo',
  [PUZZLE_BOX_ESCAPE_PROJECT_ID]: '/puzzle-box-escape-demo',
  [POCKET_RALLY_PROJECT_ID]: '/pocket-rally-time-trial-demo',
  [TRIP_PACKING_PROJECT_ID]: '/trip-packing-planner-demo',
  [FLASHCARD_CRAM_PROJECT_ID]: '/flashcard-cram-drill-demo',
  [FOLLOW_UP_CRM_PROJECT_ID]: '/follow-up-crm-tracker-demo',
  [REACTION_TRAINER_PROJECT_ID]: '/reaction-time-trainer-demo',
  [LANE_DEFENSE_PROJECT_ID]: '/tiny-lane-defense-demo',
}

export function getProjectRouteOverride(projectId: string) {
  return PROJECT_ROUTE_OVERRIDES[projectId] ?? null
}

export function getProjectHref(project: Pick<Prompt | PromptWithRelations, 'id'>) {
  return PROJECT_ROUTE_OVERRIDES[project.id] ?? `/prompt/${project.id}`
}
