-- RETIRED: legacy public Request a Build installer.
--
-- This file is intentionally non-executable. The canonical, versioned private
-- managed-service authority is:
--
--   supabase/migrations/20260730040819_request_build_private_authority_v1.sql
--
-- Do not recreate public request, response, or vote policies from an older
-- checkout. The migration fingerprints the exact empty legacy relations,
-- replaces the private request root atomically, and freezes the legacy
-- response/vote relations with all app-role access revoked.
